/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/soa/sample/TestSrvIfSomeIPStubAdapter.hpp>
#include <v1/soa/sample/TestSrvIf.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace soa {
namespace sample {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createTestSrvIfSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< TestSrvIfSomeIPStubAdapter<::v1::soa::sample::TestSrvIfStub>>(_address, _connection, _stub);
}

void initializeTestSrvIfSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:soa.sample.TestSrvIf:v1_0:TestSrvIf.server_app",
         0x382, 0x1, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "soa.sample.TestSrvIf:v1_0",
        &createTestSrvIfSomeIPStubAdapter);
}

INITIALIZER(registerTestSrvIfSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeTestSrvIfSomeIPStubAdapter);
}

} // namespace sample
} // namespace soa
} // namespace v1
