/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef SOA_SAMPLE_CUSTOM_TYPES_SOMEIP_DEPLOYMENT_HPP_
#define SOA_SAMPLE_CUSTOM_TYPES_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace soa {
namespace sample {
namespace CustomTypes_ {

// typecollection-specific deployment types
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<int16_t>,
    CommonAPI::SomeIP::IntegerDeployment<int16_t>
> PlusParamInfoDeployment_t;

typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<int64_t>,
    CommonAPI::SomeIP::IntegerDeployment<int64_t>
> TimeInfoDeployment_t;


// typecollection-specific deployments

} // namespace CustomTypes_
} // namespace sample
} // namespace soa

#endif // SOA_SAMPLE_CUSTOM_TYPES_SOMEIP_DEPLOYMENT_HPP_
